In [1]:
import numpy as np
from sympy import *

In [2]:
splus=np.array([[0,2],[0,0]])
sminus=np.array([[0,0],[2,0]])


sx=np.array([[0,1],[1,0]])
sy=np.array([[0,-1j],[1j,0]])
sz=np.array([[1,0],[0,-1]])


def conmut(A,B):
    return np.matmul(A,B)-np.matmul(B,A)


def anticonmut(A,B):
    return np.matmul(A,B)+np.matmul(B,A)

def dagger(A):
    return np.transpose(np.conjugate(A))

def mult(A,B):
    return np.matmul(A,B)

In [3]:
C=sz


np.matmul(np.matmul(splus,sz),sminus)

array([[-4,  0],
       [ 0,  0]])

In [4]:
anticonmut(sz,splus)

array([[0, 0],
       [0, 0]])

In [5]:
A=sz

B=splus


mult(mult(dagger(A),B),A)

array([[ 0, -2],
       [ 0,  0]])

In [6]:
Ago=sminus


mult(dagger(Ago),Ago)

array([[4, 0],
       [0, 0]])

In [7]:
conmut(sz,sx)

array([[ 0,  2],
       [-2,  0]])

In [8]:
mult(splus,sminus)

array([[4, 0],
       [0, 0]])

In [9]:
anticonmut(splus,sz)

array([[0, 0],
       [0, 0]])

In [19]:
conmut(sz,sy)

array([[0.+0.j, 0.-2.j],
       [0.-2.j, 0.+0.j]])